# Generated by Django 3.1.1 on 2020-09-16 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0003_auto_20200916_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[(1, 'Не ищу работу'), (2, 'Рассматриваю предложения'), (3, 'Ищу работу')], max_length=1)),
                ('salary', models.IntegerField()),
                ('grade', models.CharField(choices=[(1, 'Стажер'), (2, 'Джуниор'), (3, 'Миддл'), (4, 'Синьор'), (5, 'Лид')], max_length=1)),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('portfolio', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
