# Generated by Django 3.1.1 on 2020-09-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_auto_20200918_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_cover_letter',
            field=models.TextField(max_length=1000, verbose_name='Сопроводительное письмо'),
        ),
        migrations.AlterField(
            model_name='application',
            name='written_phone',
            field=models.CharField(max_length=10, verbose_name='Ваш телефон'),
        ),
        migrations.AlterField(
            model_name='application',
            name='written_username',
            field=models.CharField(max_length=50, verbose_name='Вас зовут'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Информация о компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(blank=True, verbose_name='Количество человек в компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='География'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='company_images', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='grade',
            field=models.CharField(choices=[(1, 'Стажер'), (2, 'Джуниор'), (3, 'Миддл'), (4, 'Синьор'), (5, 'Лид')], max_length=1, verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='portfolio',
            field=models.CharField(max_length=100, verbose_name='Ссылка на портфолио'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.IntegerField(verbose_name='Ожидаемое вознаграждение'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[(1, 'Не ищу работу'), (2, 'Рассматриваю предложения'), (3, 'Ищу работу')], max_length=1, verbose_name='Готовность к работе'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Описание вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Требуемые навыки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Название вакансии'),
        ),
    ]
