# Generated by Django 3.1.1 on 2020-09-19 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_auto_20200919_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='specialty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='vacancies.specialty'),
            preserve_default=False,
        ),
    ]
