# Generated by Django 3.1.1 on 2020-09-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_resume_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='grade',
            field=models.CharField(choices=[('1', 'Стажер'), ('2', 'Джуниор'), ('3', 'Миддл'), ('4', 'Синьор'), ('5', 'Лид')], max_length=1, verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('1', 'Не ищу работу'), ('2', 'Рассматриваю предложения'), ('3', 'Ищу работу')], max_length=1, verbose_name='Готовность к работе'),
        ),
    ]
